[theme]

# Primary accent for interactive elements
primaryColor = '#FF10F0'

# Background color for the main content area
backgroundColor = '#000010'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#5A5A5A'

# Color used for almost all text
textColor = '#FFD700'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"